name: Deploy to GitHub Pages  
on:  
  push:  
    branches: [master]  
permissions:  
  contents: write  
  pages: write  
  id-token: write  
jobs:  
  build-deploy:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout  
        uses: actions/checkout@v4  

      - name: Setup Node.js 20  
        uses: actions/setup-node@v3  
        with:  
          node-version: 20  

      - name: Install Dependencies  
        run: yarn install --frozen-lockfile  

      - name: Build Project  
        run: yarn build  

      - name: Upload Artifact  
        uses: actions/upload-pages-artifact@v3
        with:  
          path: ./dist  

      - name: Deploy to GitHub Pages  
        uses: actions/deploy-pages@v2  
